name: Student Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download classroom-assistant
        run: |
          curl -L -o classroom-assistant https://github.com/UMONS-anum/classroom-assistant-bin/raw/main/classroom-assistant
          chmod +x classroom-assistant

      - name: Run the Classroom Assistant
        run: ./classroom-assistant || echo "Failed to run"
        env:
          GH_WORKER: ${{ secrets.GH_WORKER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
