name: Student Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download classroom-assistant
        run: |
          curl -L -H "Authorization: token ${{ secrets.GH_PAT }} \
          -o classroom-assistant \
          https://github.com/UMONS-anum/classroom-assistant/releases/download/classroom-assistant/classroom-assistant

      - name: Run the Classroom Assistant
        run: ./classroom-assistant
        env:
          ACCESS_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
