name: Test Student Code

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Download the Classroom Assistant
        run: |
          curl -L -o classroom-assistant https://github.com/UMONS-anum/classroom-assistant-bin/raw/main/classroom-assistant
          chmod +x classroom-assistant

      - name: Run the Classroom Assistant
        run: |
          ls -l
          ./classroom-assistant
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
